### ISSUE TITLE
Request for documentation and examples

### ISSUE THREAD

**Issue by kookma** [clutterstack/digikam-to-tiddlywiki#1]
Jupyter notebooks are quite common nowadays. I see this tool create some integration between TW and Jupyter notebook I appreciate to add some text (documentation) to show how to use the tool

**Comment by clutterstack** [comment]
@kookma, I have updated the README file to explain better what this notebook is. All it does, TiddlyWiki-wise, is generate some text files in tiddler format that I can feed to my TW. I suppose that functionality could be made into some reusable scripts for writing tiddlers from data stored in Python variables. Is that what you were thinking of?

**Comment by kookma** [comment]
Thank you! Yes.
